from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List
from datetime import datetime
import random

from app.database import get_db
from app.models.report import GeneratedReport
from app.schemas.report import ReportResponse, ReportGenerate
from app.utils.auth import get_current_user
from app.models.user import User
from app.services.report_service import generate_actionable_insight

router = APIRouter(prefix="/api/reports", tags=["Investor Reports"])

@router.get("/", response_model=List[ReportResponse])
async def get_user_reports(
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Fetch all reports generated by the current user."""
    return db.query(GeneratedReport).filter(GeneratedReport.user_id == user.id).order_by(GeneratedReport.created_at.desc()).all()

@router.post("/generate", response_model=ReportResponse, status_code=status.HTTP_201_CREATED)
async def generate_report(
    request: ReportGenerate,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Generate an actionable, intelligence-driven report.
    """
    # 1. Fetch real actionable insights based on user data
    insight_data = await generate_actionable_insight(request.report_type, db, user.id)
    
    # 2. Extract key summary point
    summary = ""
    if request.report_type == "portfolio":
        score = insight_data.get('healthScore', 0)
        summary = f"Portfolio Health: {score}/100. Risks detected: {len(insight_data.get('risks', []))}"
    elif request.report_type == "morning":
        summary = f"Market Bias: {insight_data.get('trendBias', 'N/A')}. Breakouts found: {len(insight_data.get('topBreakouts', []))}"
    elif request.report_type == "weekly":
        best = insight_data[0] if insight_data else None
        summary = f"Top Opportunity: {best['symbol'] if best else 'N/A'} (Score {best['score'] if best else 0})"
    else:
        summary = f"AI scanning complete. Precision analysis applied to your tracked assets."

    # Simulate some report properties
    size = random.randint(1200000, 4000000) # Reports are larger now with charts data
    
    new_report = GeneratedReport(
        user_id=user.id,
        title=request.title,
        report_type=request.report_type,
        summary=summary,
        file_path=f"/static/reports/{user.id}/{request.report_type}_{int(datetime.utcnow().timestamp())}.pdf",
        size_bytes=size,
        status="completed",
        metadata_json={**request.metadata_json, "insights": insight_data}
    )
    
    db.add(new_report)
    db.commit()
    db.refresh(new_report)
    
    return new_report

@router.delete("/{report_id}")
async def delete_report(
    report_id: int,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Delete a generated report."""
    report = db.query(GeneratedReport).filter(GeneratedReport.id == report_id, GeneratedReport.user_id == user.id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
        
    db.delete(report)
    db.commit()
    
    return {"status": "success", "message": "Report deleted"}
